# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170726_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=products.models.download_location),
        ),
    ]
