# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 22:23
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/naveen/cs/digital/static_cdn/protected'), upload_to=products.models.download_location),
        ),
    ]
