# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_myproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproducts',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
